import {parseProject,aggregate,clean} from './parser.mjs';
import {budgetComparison} from './budget-comparison.mjs';
const $=id=>document.getElementById(id), esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(v,d=2)=>Number.isFinite(v)?v.toLocaleString('en-US',{minimumFractionDigits:d,maximumFractionDigits:d}):'—';
const money=(v,code='USD')=>Number.isFinite(v)?(code==='DOP'?'RD$ ':'US$ ')+fmt(v):'—';
const signed=v=>v===0?'—':(v<0?'−':'')+fmt(Math.abs(v));
const nfmt=v=>v===0?'—':fmt(v);
const pct=v=>fmt(v,1)+'%';
const diffClass=v=>v>0.005?'positive':v<-.005?'negative':'';
const clamp=v=>Math.min(100,Math.max(0,v));
const statusText={colocada:'Orden colocada',stock:'Stock / Completado',pendiente:'Pendiente de compra',sin_info:'Sin información',revisar:'Revisar'};
const COLORS={colocada:'#08725a',stock:'#78c4e3',pendiente:'#ffa142',sin_info:'#d3dce0',revisar:'#bb4545'};
const titles={resumen:'Resumen Ejecutivo',compras:'Seguimiento de Compras',presupuesto:'Presupuesto vs. Real',flujo:'Flujo de Caja',comparativo:'Comparativo Proyectos',datos:'Data General'};
const ICON={overview:'<rect x="3" y="2" width="17" height="20" rx="2"/><path d="M7 7h9M7 11h9M7 15h6"/>',purchase:'<circle cx="9" cy="7" r="4"/><path d="M3 21v-3a6 6 0 0 1 12 0v3M19 9v9m-3-3h6"/>',budget:'<path d="M5 2h11l4 4v16H5a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Z"/><path d="M15 2v5h5M7 12h9M7 16h9"/>',flow:'<rect x="3" y="5" width="18" height="16" rx="2"/><path d="M7 2h10M7 10h10M7 14h5"/><circle cx="17" cy="16" r="4"/>',compare:'<path d="M3 20V11m6 9V6m6 14v-5m6 5V3M2 5l6-3 5 7 8-5"/>',data:'<rect x="4" y="2" width="16" height="20" rx="1"/><path d="M8 7h8M8 11h8M8 15h8"/>',pdf:'<path d="M5 2h11l4 4v16H5a2 2 0 0 1-2-2V4a2 2 0 0 1 2-2Z"/><path d="M15 2v5h5M8 13h8M8 17h8"/>',coins:'<ellipse cx="12" cy="5" rx="8" ry="3"/><path d="M4 5v6c0 4 16 4 16 0V5M4 11v6c0 4 16 4 16 0v-6"/>',doc:'<rect x="5" y="2" width="13" height="20" rx="2"/><path d="M9 7h5M9 11h5M9 15h5"/>',growth:'<path d="M4 20v-6h4v6M10 20V9h4v11M16 20V4h4v16"/>',cart:'<circle cx="10" cy="20" r="1"/><circle cx="19" cy="20" r="1"/><path d="M2 3h3l3 13h12l2-10H6"/>',clock:'<circle cx="12" cy="12" r="10"/><path d="M12 6v6l4 3"/>'};
function icon(name){return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 24 24" aria-hidden="true">${ICON[name]||ICON.doc}</svg>`;}
document.querySelectorAll('[data-icon]').forEach(e=>e.innerHTML=icon(e.dataset.icon));
let saved=[],view='resumen',selected='__all',selectedFormat='__all',selectedType='__all',selectedYear='__all',selectedQuarter='__all';
let preview=true,budgetDonut='partidas',purchaseFilter='__all',search='',openBudget=new Set(['demo|1.00','demo|2.00']),openCash=new Set(),openSummary=new Set(),openCompare=new Set(),storageOk=true;
const DB='ramos_iniciativas_dashboard_v2',ST='projects';
function db(){return new Promise((yes,no)=>{const req=indexedDB.open(DB,1);req.onupgradeneeded=()=>req.result.createObjectStore(ST,{keyPath:'id'});req.onsuccess=()=>yes(req.result);req.onerror=()=>no(req.error);});}
function allProjects(){return new Promise(async(yes,no)=>{try{const d=await db(),t=d.transaction(ST,'readonly'),r=t.objectStore(ST).getAll();r.onsuccess=()=>yes(r.result||[]);r.onerror=()=>no(r.error);t.oncomplete=()=>d.close();}catch(e){no(e);}});}
function storeProject(p){return new Promise(async(yes,no)=>{try{const d=await db(),t=d.transaction(ST,'readwrite');t.objectStore(ST).put(p);t.oncomplete=()=>{d.close();yes();};t.onerror=()=>no(t.error);}catch(e){no(e);}});}
function dropProject(id){return new Promise(async(yes,no)=>{try{const d=await db(),t=d.transaction(ST,'readwrite');t.objectStore(ST).delete(id);t.oncomplete=()=>{d.close();yes();};t.onerror=()=>no(t.error);}catch(e){no(e);}});}
function toast(msg,bad=false){const t=$('toast');t.textContent=msg;t.style.background=bad?'#a53d37':'#104b5c';t.hidden=false;clearTimeout(toast.t);toast.t=setTimeout(()=>t.hidden=true,4500);}
function guessFormat(name){const t=clean(name);return t.includes('aprezio')?'Aprezio':t.includes('sirena')?'Sirena':'Sin clasificar';}
function guessType(name){const t=clean(name);return /remodel|adecuacion|ampliacion/.test(t)?'Remodelación':/nueva|nuevo|apertura/.test(t)?'Nueva':'Sin clasificar';}
function meta(p){return {format:p.format||guessFormat(p.name),type:p.projectType||guessType(p.name)};}
const demo={id:'demo',name:'Sirena Compacta Hispano',filename:'DEMO.xlsx',format:'Sirena',projectType:'Nueva',startYear:2026,importedAt:null,parserVersion:2,demo:true,
  selected:{purchases:'BD Plan Detallado',budget:'Presupuesto Vs Real',cashflow:'Flujo de Caja'},warnings:[],
  budget:{totals:{presupuesto:3466781.75,real:3084613.65,source:'total_general'},summaryCategories:[{label:'Equipamiento',presupuesto:3218444.48,real:2825389.21},{label:'Edificación',presupuesto:248337.27,real:259224.43},{label:'Terreno',presupuesto:0,real:0},{label:'Gasto',presupuesto:0,real:0}],groups:[
    {code:'1.00',label:'Estudios Preliminares',presupuesto:0,real:0,children:[{code:'1.01',label:'Diseño arquitectónico',presupuesto:0,real:0},{code:'1.02',label:'Diseño estructural',presupuesto:0,real:0},{code:'1.03',label:'Diseño electromecánico',presupuesto:0,real:0}]},
    {code:'2.00',label:'Obra Civil',presupuesto:248337.27,real:259224.43,children:[{code:'2.01',label:'Edificación - Obra Civil',presupuesto:12458.73,real:17685.78},{code:'2.02',label:'Edificación - Estructura Metálica',presupuesto:0,real:0},{code:'2.03',label:'Edificación - Techo S.S. y Cerramientos Multipanel',presupuesto:0,real:0},{code:'2.05',label:'Instalaciones Sanitarias',presupuesto:25100,real:19376.54},{code:'2.06',label:'Instalación de Gas',presupuesto:7487.64,real:7487.64},{code:'2.07',label:'Sistema Contra Incendios',presupuesto:100582.35,real:111965.92},{code:'2.08',label:'Instalaciones Mecánicas',presupuesto:87881.53,real:87881.53},{code:'2.09',label:'Rejillas y Sumideros',presupuesto:14827.02,real:14827.02}]},
    {code:'3.00',label:'Equipamiento',presupuesto:3218444.48,real:2825389.21,children:[]} ]},
  cashflow:{periods:Array.from({length:22},(_,i)=>({id:i+1,yearIndex:Math.floor(i/12)+1,month:['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'][i%12]})),groups:[],totals:[],fxRate:63},
  purchases:{rows:[]}};
{
 const first=['Refrigeración','Mobiliario','Sistema contra incendios','Equipo de panadería','Instalación sanitaria','Góndolas'];
 for(let i=0;i<114;i++){const estado=i<72?'colocada':i<80?'stock':'pendiente';demo.purchases.rows.push({row:5+i,partida:i%4===0?'Equipamiento':'Obra Civil',item:(first[i%6])+' · ejemplo '+(i+1),oc:estado==='colocada'?'4500'+String(101000+i):estado==='stock'?'Stock':'Pendiente de compra',estado,proveedor:'Proveedor de muestra',presupuestoDOP:125000+i*800});}
 const cash=[60000,90000,190000,70000,130000,360000,550000,1100000,250000,370000,400000,450000,590000,650000,320000,200000,340000,475000,515000,525000,600000,135000];
 demo.cashflow.totals=cash.map(v=>v*63);demo.cashflow.groups=[{code:'2.00',label:'Obra Civil',presupuesto:cash.reduce((s,v)=>s+v*63,0),values:cash.map(v=>v*63),children:[{code:'2.01',label:'Edificación - Obra Civil',presupuesto:cash.reduce((s,v)=>s+v*63,0),values:cash.map(v=>v*63)}]}];
}
const displayProjects=()=>saved.length?saved:preview?[demo]:[];
const matchSearch=(...parts)=>!search||clean(parts.join(' ')).includes(clean(search));
function filtersProjects(){return displayProjects().filter(p=>(selected==='__all'||p.id===selected)&&(selectedFormat==='__all'||meta(p).format===selectedFormat)&&(selectedType==='__all'||meta(p).type===selectedType));}
function fillSelect(id,options,current){const el=$(id);el.innerHTML=options.map(([value,label])=>`<option value="${esc(value)}">${esc(label)}</option>`).join('');el.value=options.some(([v])=>v===current)?current:'__all';}
function syncFilters(){const all=displayProjects();fillSelect('projectSelect',[['__all','Todos los proyectos'],...all.map(p=>[p.id,p.name])],selected);fillSelect('formatSelect',[['__all','Todos'],...[...new Set(all.map(p=>meta(p).format))].sort().map(x=>[x,x])],selectedFormat);fillSelect('typeSelect',[['__all','Todos'],...[...new Set(all.map(p=>meta(p).type))].sort().map(x=>[x,x])],selectedType);
 const years=[...new Set(all.flatMap(p=>p.cashflow.periods.map(t=>Number.isInteger(p.startYear)?p.startYear+t.yearIndex-1:null).filter(Boolean)))].sort();fillSelect('yearSelect',[['__all','Todos'],...years.map(y=>[String(y),String(y)])],selectedYear);
 $('sideUpdate').textContent=saved.length?new Date(Math.max(...saved.map(x=>new Date(x.importedAt||0).getTime()||0))).toLocaleDateString('es-DO'):'Sin archivos';
 $('dataStatus').textContent=saved.length?`${saved.length} ${saved.length===1?'iniciativa cargada':'iniciativas cargadas'} · Procesamiento local · Año/trimestre filtran el flujo`:'Vista de demostración · Importa tus Excel para utilizar cifras reales';
}
function warnings(list){let warn=[];for(const p of list)if(!p.demo){if((p.parserVersion||1)<2)warn.push(`${p.name}: vuelve a cargar el Excel para usar columnas G y H`);warn.push(...(p.warnings||[]).map(s=>`${p.name}: ${s}`));}return warn.map(s=>`<div class="warning">${esc(s)}</div>`).join('');}
function render(){document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b.dataset.view===view));syncFilters();const list=filtersProjects();$('notices').innerHTML=warnings(list);
 if(!displayProjects().length){$('dashboardBody').innerHTML=`<div class="empty-state"><h2>Empieza cargando tus iniciativas</h2><p>Selecciona uno o varios archivos Excel con las hojas BD Plan Detallado, Presupuesto Vs Real y Flujo de Caja. También puedes activar la vista de demostración.</p><button id="emptyUpload">＋ Cargar Excel</button> <button id="enableDemo" class="control-btn">Ver demostración</button></div>`;bindBody();return;}
 if(list.length===0){$('dashboardBody').innerHTML=`<div class="empty-state"><h2>No hay proyectos con esos filtros</h2><p>Cambia Proyecto, Formato o Tipo de proyecto en la cabecera.</p></div>`;return;}
 const badge=list.some(p=>p.demo)?`<div class="demo-notice"><b>VISTA DEMOSTRATIVA · DATOS DE EJEMPLO.</b> El diseño es funcional; los montos de esta vista solo sirven para visualizarlo. <button id="demoUpload">Cargar mis Excel</button></div>`:'';
 let body='';if(view==='resumen')body=summary(list);if(view==='compras')body=purchasesView(list);if(view==='presupuesto')body=budgetView(list);if(view==='flujo')body=cashView(list);if(view==='comparativo')body=compareView(list);if(view==='datos')body=dataView(list);
 $('dashboardBody').innerHTML=badge+body;bindBody();}
function card(label,value,kind,iconName,note,progress=null){return `<article class="panel kpi-card"><span class="kpi-symbol ${kind==='good'?'green':''}">${icon(iconName)}</span><div class="kpi-name">${label}</div><div class="kpi-number ${kind==='good'?'good':kind==='bad'?'bad':''}">${value}</div>${progress!=null?`<div class="kpi-progress"><span style="width:${clamp(progress)}%"></span></div>`:''}<div class="kpi-note ${kind==='good'?'good':kind==='bad'?'bad':''}">${note}</div></article>`;}
function headerCards(list){const a=aggregate(list),classified=a.totalItems-a.sin_info-a.revisar;
 return `<div class="kpi-row">${card('Presupuesto Total',money(a.presupuesto),'','coins','100%',100)}${card('Real Ejecutado',money(a.real),'','doc',`${pct(a.presupuesto?a.real/a.presupuesto*100:0)} del presupuesto`,a.presupuesto?a.real/a.presupuesto*100:0)}${card('Diferencia',money(a.diferencia),a.diferencia>=0?'good':'bad','growth',`${a.diferencia>=0?'▲':'▼'} ${pct(a.presupuesto?Math.abs(a.diferencia)/a.presupuesto*100:0)}`)}${card('Órdenes Colocadas',fmt(a.colocada,0),'','cart',`${pct(classified?a.colocada/classified*100:0)} de ítems clasificados`,classified?a.colocada/classified*100:0)}${card('Pendientes de Compra',fmt(a.pendiente,0),'','clock',`${pct(classified?a.pendiente/classified*100:0)} de ítems clasificados`,classified?a.pendiente/classified*100:0)}</div>`;}
function allGroups(list){return list.flatMap(p=>p.budget.groups.map(g=>({...g,project:p.name,projectId:p.id})));}
function categorySummary(list){const bucket=new Map();let hasSummary=false;
 for(const p of list){const cats=p.budget.summaryCategories||[];if(cats.length){hasSummary=true;for(const c of cats){let row=bucket.get(clean(c.label));if(!row){row={code:clean(c.label),label:c.label,presupuesto:0,real:0,children:[]};bucket.set(clean(c.label),row);}row.presupuesto+=c.presupuesto;row.real+=c.real;}}
 else for(const g of p.budget.groups){let row=bucket.get(g.code);if(!row){row={code:g.code,label:g.label,presupuesto:0,real:0,children:[]};bucket.set(g.code,row);}row.presupuesto+=g.presupuesto;row.real+=g.real;}}
 return {categories:[...bucket.values()],hasSummary};
}
function overviewTable(list){const {categories}=categorySummary(list),k=aggregate(list),rows=categories.filter(c=>matchSearch(c.label,c.code)).map(c=>{const id='o_'+c.code,isOpen=openSummary.has(id),matches=allGroups(list).filter(g=>{const l=clean(c.label),t=clean(g.label);return (l.includes('edifica')&&(/obra|edifica|construc/.test(t)))||(l.includes('equipa')&&(/equipa|refrigera|mobiliario/.test(t)));});const children=matches.filter(g=>g.code!==c.code);
 return `<tr><td><button data-overview="${esc(id)}" class="toggle-row"><span class="arrow">${isOpen?'⌄':'›'}</span>${esc(c.label)}</button></td><td class="num">${nfmt(c.presupuesto)}</td><td class="num">${nfmt(c.real)}</td><td class="num ${diffClass(c.presupuesto-c.real)}">${signed(c.presupuesto-c.real)}</td><td class="num ${diffClass(c.presupuesto-c.real)}">${c.presupuesto?pct((c.presupuesto-c.real)/c.presupuesto*100):'—'}</td></tr>`+(isOpen?children.map(g=>`<tr class="child"><td>${esc(g.code)} ${esc(g.label)}</td><td class="num">${nfmt(g.presupuesto)}</td><td class="num">${nfmt(g.real)}</td><td class="num ${diffClass(g.presupuesto-g.real)}">${signed(g.presupuesto-g.real)}</td><td class="num">${g.presupuesto?pct((g.presupuesto-g.real)/g.presupuesto*100):'—'}</td></tr>`).join(''):'');}).join('');
 return `<div class="table-wrap"><table class="data-table"><thead><tr><th>Partida</th><th class="num">Presupuestado (USD)</th><th class="num">Real (USD)</th><th class="num">Diferencia (USD)</th><th class="num">% Desviación</th></tr></thead><tbody>${rows||'<tr><td colspan="5" class="empty-inline">Sin partidas</td></tr>'}<tr class="grand"><td>Total General</td><td class="num">${fmt(k.presupuesto)}</td><td class="num">${fmt(k.real)}</td><td class="num ${diffClass(k.diferencia)}">${fmt(k.diferencia)}</td><td class="num ${diffClass(k.diferencia)}">${k.presupuesto?pct(k.diferencia/k.presupuesto*100):'—'}</td></tr></tbody></table></div>`;}
function donut(items,total,center,legendClass='',centerSub=''){if(!total)return `<div class="no-data">Sin datos para distribución.</div>`;
 let pos=0;const gradients=[];for(const r of items){if(!r.value)continue;const n=Math.min(100,r.value/total*100);gradients.push(`${r.color} ${pos}% ${pos+n}%`);pos+=n;}if(pos<99.999)gradients.push(`#edf2f4 ${pos}% 100%`);
 return `<div class="viz-layout ${legendClass}"><div class="donut" style="background:conic-gradient(${gradients.join(',')})"><div class="donut-center">${center}<small style="display:block;font-size:14px;font-weight:500">${centerSub}</small></div></div><div class="budget-legend">${items.filter(x=>x.value||x.show).map(x=>`<div class="leg-item"><span class="dot" style="background:${x.color}"></span><div><b>${esc(x.label)}</b><small>${esc(x.detail||'')}</small></div></div>`).join('')}</div></div>`;}
function budgetDonutHtml(list){let items=[],palette=['#0b6077','#318faf','#96999b','#ccdce3','#f7a45c','#196c55'];if(budgetDonut==='proyectos')items=list.map((p,i)=>({label:p.name,value:p.budget.totals.presupuesto||0,color:palette[i%palette.length],detail:money(p.budget.totals.presupuesto)}));else items=categorySummary(list).categories.map((c,i)=>({label:c.label,value:c.presupuesto,color:palette[i%palette.length],detail:money(c.presupuesto),show:i<4}));const total=items.reduce((s,x)=>s+Math.max(0,x.value),0);return donut(items,total,`<span style="font-size:14px">US$</span><strong style="font-size:22px">${fmt(total/1e6,2)} M</strong>`,'', '');}
function stateDonut(list){const k=aggregate(list),total=k.totalItems,items=[{label:'Orden colocada',value:k.colocada,color:COLORS.colocada,detail:`${k.colocada} (${pct(total?k.colocada/total*100:0)})`},{label:'Stock / Completado',value:k.stock,color:COLORS.stock,detail:`${k.stock} (${pct(total?k.stock/total*100:0)})`},{label:'Pendiente',value:k.pendiente,color:COLORS.pendiente,detail:`${k.pendiente} (${pct(total?k.pendiente/total*100:0)})`},{label:'Por revisar',value:k.sin_info+k.revisar,color:'#bdcbd0',detail:`${k.sin_info+k.revisar}`,show:k.sin_info+k.revisar>0}];return donut(items,total,`<strong>${fmt(total,0)}</strong>`,'purchase-viz','ítems');}
function groupRow(g,p,overview=false){const key=`${p.id}|${g.code}`,isOpen=openBudget.has(key);if(!matchSearch(g.code,g.label,...(g.children||[]).map(c=>c.label)))return '';
 const base=`<tr class="parent"><td><button class="toggle-row" data-budget-toggle="${esc(key)}" aria-expanded="${isOpen}"><span class="arrow">${isOpen?'⌄':'›'}</span>${esc(g.code)} ${esc(g.label)}</button></td><td class="num">${nfmt(g.presupuesto)}</td><td class="num">${nfmt(g.real)}</td><td class="num ${diffClass(g.presupuesto-g.real)}">${signed(g.presupuesto-g.real)}</td><td class="num ${diffClass(g.presupuesto-g.real)}">${g.presupuesto?pct((g.presupuesto-g.real)/g.presupuesto*100):'—'}</td></tr>`;
 return base+(isOpen?(g.children||[]).filter(c=>matchSearch(g.label,g.code,c.code,c.label)).map(c=>`<tr class="child"><td>${esc(c.code)} ${esc(c.label)}</td><td class="num">${nfmt(c.presupuesto)}</td><td class="num">${nfmt(c.real)}</td><td class="num ${diffClass(c.presupuesto-c.real)}">${signed(c.presupuesto-c.real)}</td><td class="num ${diffClass(c.presupuesto-c.real)}">${c.presupuesto?pct((c.presupuesto-c.real)/c.presupuesto*100):'—'}</td></tr>`).join(''):'');}
function budgetMatrix(list,limit=false){if(list.length>1)return compareTable(list,true);const p=list[0],rows=p.budget.groups.map(g=>groupRow(g,p,true)).join('');const k=aggregate(list);
 return `<div class="table-wrap ${limit?'scroll-body':''}"><table class="data-table"><thead><tr><th>Partida / Subpartida</th><th class="num">Presupuestado (USD)</th><th class="num">Real (USD)</th><th class="num">Diferencia (USD)</th><th class="num">% Desviación</th></tr></thead><tbody>${rows||'<tr><td colspan="5">No hay partidas reconocibles.</td></tr>'}${limit?'':`<tr class="grand"><td>TOTAL GENERAL</td><td class="num">${fmt(k.presupuesto)}</td><td class="num">${fmt(k.real)}</td><td class="num ${diffClass(k.diferencia)}">${fmt(k.diferencia)}</td><td class="num">${k.presupuesto?pct(k.diferencia/k.presupuesto*100):'—'}</td></tr>`}</tbody></table></div>`;}
function periodRows(list){const map=new Map();for(const p of list){p.cashflow.periods.forEach((t,i)=>{const year=Number.isInteger(p.startYear)?p.startYear+t.yearIndex-1:null;const id=year!=null?year*12+(['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].findIndex(m=>clean(m)===clean(t.month))):t.id;let v=map.get(id);if(!v){v={id,period:t.id,yearIndex:t.yearIndex,month:t.month,year,planned:0,sourceCurrency:'DOP'};map.set(id,v);}v.planned+=p.cashflow.totals[i]||0;});}return [...map.values()].sort((a,b)=>a.id-b.id);}
function filterPeriods(list){return periodRows(list).filter(t=>(selectedYear==='__all'||String(t.year||'')===selectedYear)&&(selectedQuarter==='__all'||String(Math.floor((['enero','febrero','marzo','abril','mayo','junio','julio','agosto','septiembre','octubre','noviembre','diciembre'].indexOf(clean(t.month)))/3)+1)===selectedQuarter));}
function cashChart(list){let periods=filterPeriods(list);if(!periods.length)return `<div class="no-data">No hay períodos para los filtros seleccionados. Si falta el año, configúralo en «Gestionar proyectos».</div>`;
 const fx=list.length===1?list[0].cashflow.fxRate:null,currency=fx>0?'USD':'DOP';const monthly=periods.map(p=>({...p,amount:currency==='USD'?p.planned/fx:p.planned}));const mx=Math.max(...monthly.map(p=>p.amount),1)*1.2;
 const W=1240,H=158,L=58,R=10,T=13,B=26,pw=W-L-R,ph=H-T-B,barW=pw/monthly.length*.53;const grid=[0,.25,.5,.75,1].map(f=>{const y=T+ph-f*ph;const value=mx*f;const label=value>=1e6?fmt(value/1e6,1)+'M':value>=1000?fmt(value/1000,0)+'K':fmt(value,0);return `<line x1="${L}" y1="${y}" x2="${W-R}" y2="${y}" stroke="#dfe9ef"/><text x="${L-8}" y="${y+4}" text-anchor="end" fill="#677d89" font-size="10">${label}</text>`;}).join('');
 const bars=monthly.map((p,i)=>{const w=pw/monthly.length,x=L+(i+.5)*w-barW/2,y=T+ph-p.amount/mx*ph;return `<rect x="${x}" y="${y}" width="${barW}" height="${T+ph-y}" fill="#1b7592" rx=".8"><title>${esc(p.month)} ${p.year||'Año '+p.yearIndex}: ${money(p.amount,currency)}</title></rect><text x="${x+barW/2}" y="${H-9}" text-anchor="middle" fill="#2a4960" font-size="10">${esc(p.month.slice(0,3))}</text>`;}).join('');
 const years=monthly.reduce((arr,p)=>{const y=p.year||'Año '+p.yearIndex;let cur=arr[arr.length-1];if(!cur||cur.label!==y){cur={label:y,count:0};arr.push(cur);}cur.count++;return arr;},[]);
 return `<div class="section-heading" style="padding:0 0 4px"><h2 class="section-title">Flujo de Caja Mensual (${currency})</h2><div class="legend-mini"><span><span class="dot plan"></span>Programado</span></div></div><svg class="cash-chart" role="img" aria-label="Flujo mensual programado en ${currency}" viewBox="0 0 ${W} ${H}" preserveAspectRatio="none">${grid}${bars}</svg><div class="cash-years">${years.map(y=>`<span style="flex:${y.count}">${esc(y.label)}</span>`).join('')}</div>`;}
function summary(list){return headerCards(list)+`<div class="two-col"><section class="panel card-section"><div class="section-heading"><h2 class="section-title">Presupuesto vs. Real por Partida</h2><div class="legend-mini"><span><i class="dot plan"></i>Presupuestado</span><span><i class="dot real"></i>Real</span><span><i class="dot diff"></i>Diferencia</span></div></div>${overviewTable(list)}</section><section class="panel card-section"><div class="section-heading"><h2 class="section-title">Distribución del Presupuesto</h2><div class="segmented"><button data-donut="partidas" class="${budgetDonut==='partidas'?'active':''}">Por partida</button><button data-donut="proyectos" class="${budgetDonut==='proyectos'?'active':''}">Por proyecto</button></div></div>${budgetDonutHtml(list)}</section></div>
 <div class="two-col detail-row"><section class="panel card-section"><div class="section-heading"><h2 class="section-title">Detalle por Partida y Subpartida</h2><div class="card-tools"><button data-expand="${list.length>1?'compare':'budget'}" class="control-btn">Expandir</button><button data-collapse="${list.length>1?'compare':'budget'}" class="control-btn">Contraer</button></div></div>${budgetMatrix(list,true)}</section><section class="panel card-section"><div class="section-heading"><h2 class="section-title">Avance de Compras</h2></div>${stateDonut(list)}</section></div><section class="panel bottom-panel">${cashChart(list)}</section>`;}
function purchasesView(list){const k=aggregate(list),rows=list.flatMap(p=>p.purchases.rows.map(r=>({...r,project:p.name}))).filter(r=>matchSearch(r.item,r.partida,r.oc,r.proveedor,r.project));const filtered=rows.filter(r=>purchaseFilter==='__all'||r.estado===purchaseFilter);
 return `<div class="kpi-row">${card('Total de Ítems',fmt(k.totalItems,0),'','doc','Registrados en BD Plan Detallado')}${card('Órdenes Colocadas',fmt(k.colocada,0),'','cart','Detectadas en columna G')}${card('Stock / Completado',fmt(k.stock,0),'good','coins','Identificadas como Stock')}${card('Pendientes',fmt(k.pendiente,0),'bad','clock','Pendientes de compra')}${card('Avance Gestionado',pct(k.avance),'good','growth','OC colocada + stock',k.avance)}</div><div class="two-col"><section class="panel card-section"><div class="section-heading"><h2 class="section-title">Estado de las Compras</h2></div>${stateDonut(list)}</section><section class="panel card-section"><div class="section-heading"><h2 class="section-title">Seguimiento por Iniciativa</h2></div><div class="bar-chart-list">${list.map(p=>{const a=aggregate([p]);return `<div><div class="bar-caption"><strong>${esc(p.name)}</strong><b>${pct(a.avance)}</b></div><div class="bar-track"><div class="bar-fill" style="width:${clamp(a.avance)}%"></div></div><small>${a.colocada} órdenes · ${a.stock} stock · ${a.pendiente} pendientes</small></div>`;}).join('')}</div></section></div><section class="panel module-panel"><div class="toolbar"><div><h2 class="section-title">Detalle de Órdenes y Materiales</h2><small>Clasificación automática desde la columna G. «Revisar» y «Sin información» no cuentan en el avance.</small></div><div class="card-tools"><input id="searchInput" class="search-field" placeholder="Buscar partida, ítem, proveedor…" value="${esc(search)}"><select id="purchaseFilter" class="control-btn"><option value="__all">Todos los estados</option>${Object.entries(statusText).map(([value,label])=>`<option value="${value}" ${purchaseFilter===value?'selected':''}>${label}</option>`).join('')}</select><button class="control-btn" id="exportPurchases">Exportar CSV</button></div></div><div class="table-wrap" style="max-height:560px"><table class="data-table"><thead><tr><th>Proyecto</th><th>Partida</th><th>Ítem</th><th>Orden compra (G)</th><th>Estado</th><th>Proveedor</th><th class="num">Monto de referencia (DOP)</th></tr></thead><tbody>${filtered.slice(0,900).map(r=>`<tr><td>${esc(r.project)}</td><td>${esc(r.partida)}</td><td>${esc(r.item)}</td><td>${esc(r.oc)}</td><td><span class="pill ${r.estado}">${statusText[r.estado]}</span></td><td>${esc(r.proveedor)}</td><td class="num">${nfmt(r.presupuestoDOP)}</td></tr>`).join('')||'<tr><td colspan="7">Sin ítems para el filtro.</td></tr>'}</tbody></table></div><p class="small-note">${filtered.length>900?`Se muestran 900 de ${filtered.length} filas. Exporta CSV para ver todas. `:''}Los importes por ítem son informativos y no se suman como presupuesto general del proyecto.</p></section>`;}
function budgetView(list){return headerCards(list)+`<section class="panel module-panel"><div class="toolbar"><div><h2 class="section-title">Matriz de Presupuesto vs. Real por Partida</h2><small>Presupuesto = columna G · Real = columna H · Diferencia = Presupuesto − Real</small></div><div class="card-tools"><input id="searchInput" class="search-field" placeholder="Buscar partida…" value="${esc(search)}"><button class="control-btn" data-expand="budget">Expandir todo</button><button class="control-btn" data-collapse="budget">Contraer todo</button><button class="control-btn" id="exportBudget">Exportar CSV</button></div></div>${budgetMatrix(list)}<p class="small-note">Los renglones 1.00, 2.00… se muestran como subtotales. No se suman nuevamente con 1.01, 2.01… El TOTAL GENERAL usa el total oficial de la hoja cuando existe.</p></section>`;}
function compareTable(list,compact=false){const c=budgetComparison(list);const valueCells=v=>v?`<td class="num">${nfmt(v.presupuesto)}</td><td class="num">${nfmt(v.real)}</td><td class="num ${diffClass(v.presupuesto-v.real)}">${signed(v.presupuesto-v.real)}</td>`:'<td class="num soft">—</td><td class="num soft">—</td><td class="num soft">—</td>';
 const rows=c.rows.filter(g=>matchSearch(g.code,g.label,...g.children.map(x=>x.label))).map(g=>{const isOpen=openCompare.has(g.code);return `<tr class="parent"><td><button class="toggle-row" data-compare="${esc(g.code)}" aria-expanded="${isOpen}"><span class="arrow">${isOpen?'⌄':'›'}</span>${esc(g.code)} ${esc(g.label)}</button></td>${list.map(p=>valueCells(g.projectGroups.get(p.id))).join('')}</tr>`+(isOpen?g.children.map(ch=>`<tr class="child"><td>${esc(ch.code)} ${esc(ch.label)}</td>${list.map(p=>valueCells(ch.values.get(p.id))).join('')}</tr>`).join(''):'');}).join('');
 return `<div class="table-wrap ${compact?'scroll-body':''}"><table class="data-table comptable"><thead><tr><th rowspan="2">Partida / Subpartida</th>${list.map(p=>`<th class="group-head" colspan="3">${esc(p.name)}</th>`).join('')}</tr><tr>${list.map(()=>'<th class="num">Plan USD</th><th class="num">Real USD</th><th class="num">Diferencia USD</th>').join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${1+list.length*3}">Sin partidas</td></tr>`}${compact?'':`<tr class="grand"><td>TOTAL GENERAL</td>${list.map(p=>valueCells(c.totals.get(p.id))).join('')}</tr>`}</tbody></table></div>`;}
function compareView(list){if(list.length<2)return headerCards(list)+`<section class="panel module-panel"><h2 class="section-title">Comparativo por Proyectos</h2><div class="no-data">Carga dos o más iniciativas y selecciona «Todos los proyectos» para ver Plan, Real y Diferencia uno al lado del otro.</div></section>`;return headerCards(list)+`<section class="panel module-panel"><div class="toolbar"><div><h2 class="section-title">Plan y Real por Partida · Proyectos Lado a Lado</h2><small>Una fila por partida y tres columnas por proyecto: Plan, Real y Diferencia</small></div><div class="card-tools"><input id="searchInput" class="search-field" placeholder="Buscar partida…" value="${esc(search)}"><button class="control-btn" data-expand="compare">Expandir todo</button><button class="control-btn" data-collapse="compare">Contraer todo</button><button class="control-btn" id="exportCompare">Exportar CSV</button></div></div>${compareTable(list)}<p class="small-note">Los proyectos se alinean por número de partida. Las partidas principales no se suman con las subpartidas en el total.</p></section>`;}
function cashView(list){const filtered=filterPeriods(list),total=filtered.reduce((s,t)=>s+t.planned,0),overall=periodRows(list).reduce((s,t)=>s+t.planned,0),max=filtered.reduce((a,b)=>a.planned>b.planned?a:b,{planned:0}),allPeriods=periodRows(list);
 let cols=filtered;const budgetOI=list.reduce((s,p)=>s+p.cashflow.groups.reduce((v,g)=>v+(g.children.length?g.children.reduce((a,c)=>a+(c.presupuesto||0),0):(g.presupuesto||0)),0),0);const tableRows=[];for(const p of list)for(const g of p.cashflow.groups){const key=p.id+'|'+g.code,show=openCash.has(key);if(!matchSearch(g.code,g.label,p.name,...(g.children||[]).map(x=>x.label)))continue;const amountFor=(item,t)=>{const i=p.cashflow.periods.findIndex(pp=>(Number.isInteger(p.startYear)&&t.year!=null?(p.startYear+pp.yearIndex-1===t.year&&clean(pp.month)===clean(t.month)):(pp.id===t.period)));return i>=0?item.values?.[i]||0:0;};const fmtCells=item=>cols.map(t=>`<td class="num">${nfmt(amountFor(item,t))}</td>`).join('');const rowTotal=item=>cols.reduce((s,t)=>s+amountFor(item,t),0);
 tableRows.push(`<tr class="parent"><td><button class="toggle-row" data-cash="${esc(key)}"><span class="arrow">${show?'⌄':'›'}</span>${esc(p.name)} · ${esc(g.code)} ${esc(g.label)}</button></td><td class="num">${nfmt(g.presupuesto)}</td>${fmtCells({values:g.detailTotals||g.values})}<td class="num">${nfmt(rowTotal({values:g.detailTotals||g.values}))}</td></tr>`);
 if(show)tableRows.push(...(g.children||[]).map(ch=>`<tr class="child"><td>${esc(ch.code)} ${esc(ch.label)}</td><td class="num">${nfmt(ch.presupuesto)}</td>${fmtCells(ch)}<td class="num">${nfmt(rowTotal(ch))}</td></tr>`));}
 return `<div class="kpi-row">${card('Flujo Programado',money(overall,'DOP'),'','coins','Total de períodos')}${card('Flujo Filtrado',money(total,'DOP'),'','doc','Selección año/trimestre')}${card('Períodos',String(filtered.length),'','flow',`de ${allPeriods.length} períodos`)}${card('Pico de Desembolso',money(max.planned,'DOP'),'','growth',max.month||'Sin datos')}${card('Iniciativas',String(list.length),'','budget','Proyectos en la selección')}</div><section class="panel bottom-panel" style="margin-bottom:14px">${cashChart(list)}<p class="small-note">El Excel proporciona flujo programado; no se inventa una serie de pagos reales mensuales. Se muestra en USD solamente cuando hay una tasa USD válida en el archivo.</p></section><section class="panel module-panel"><div class="toolbar"><div><h2 class="section-title">Flujo de Caja por Partida y Mes</h2><small>Solo se suman los detalles. Excluimos subtotales, TOTAL-DOP, controles, tasa y flujo USD de los grandes totales.</small></div><div class="card-tools"><button class="control-btn" data-expand="cash">Expandir todo</button><button class="control-btn" data-collapse="cash">Contraer todo</button><button class="control-btn" id="exportCash">Exportar CSV</button></div></div><div class="table-wrap"><table class="data-table cash-matrix"><thead><tr><th>Partida / Subpartida</th><th class="num">Ppto OI (DOP)</th>${cols.map(t=>`<th class="num">${esc(t.month.slice(0,3))}${t.year?' '+t.year:' · P'+t.period}</th>`).join('')}<th class="num">Total DOP</th></tr></thead><tbody>${tableRows.join('')||`<tr><td colspan="${cols.length+3}">Sin partidas para estos filtros</td></tr>`}<tr class="grand"><td>TOTAL GENERAL SIN DUPLICACIONES</td><td class="num">${nfmt(budgetOI)}</td>${cols.map(t=>`<td class="num">${nfmt(t.planned)}</td>`).join('')}<td class="num">${nfmt(total)}</td></tr></tbody></table></div></section>`;}
function dataView(list){const agg=aggregate(list);return headerCards(list)+`<section class="panel module-panel"><div class="toolbar"><div><h2 class="section-title">Data General del Portafolio</h2><small>Resumen financiero por iniciativa, con categorías y cantidad de ítems.</small></div><button class="control-btn" id="dataManage">Editar datos de los proyectos</button></div><div class="table-wrap"><table class="data-table"><thead><tr><th>Proyecto</th><th>Formato</th><th>Tipo</th><th class="num">Presupuesto USD</th><th class="num">Real USD</th><th class="num">Diferencia USD</th><th class="num">OC</th><th class="num">Stock</th><th class="num">Pendientes</th></tr></thead><tbody>${list.map(p=>{const a=aggregate([p]);return `<tr><td>${esc(p.name)}</td><td>${esc(meta(p).format)}</td><td>${esc(meta(p).type)}</td><td class="num">${fmt(a.presupuesto)}</td><td class="num">${fmt(a.real)}</td><td class="num ${diffClass(a.diferencia)}">${signed(a.diferencia)}</td><td class="num">${a.colocada}</td><td class="num">${a.stock}</td><td class="num">${a.pendiente}</td></tr>`;}).join('')}<tr class="grand"><td>TOTAL</td><td></td><td></td><td class="num">${fmt(agg.presupuesto)}</td><td class="num">${fmt(agg.real)}</td><td class="num">${fmt(agg.diferencia)}</td><td class="num">${agg.colocada}</td><td class="num">${agg.stock}</td><td class="num">${agg.pendiente}</td></tr></tbody></table></div></section><section class="panel module-panel"><h2 class="section-title">Estructura de Lectura</h2><div class="metric-strip"><span><b>BD Plan Detallado:</b> compras de columna G</span><span><b>Presupuesto Vs Real:</b> G = Plan · H = Real</span><span><b>Flujo de Caja:</b> P1, P2… · detalle sin duplicaciones</span></div><p class="small-note">Al cargar un Excel nuevo, se incorpora a la lista de proyectos. Si subes el mismo nombre de archivo nuevamente puedes actualizarlo. Los archivos originales no se publican en GitHub y la información se conserva únicamente en este navegador mediante IndexedDB.</p></section>`;}
function csv(filename,header,rows){const quote=s=>'"'+String(s??'').replace(/"/g,'""')+'"';const content='\ufeff'+[header,...rows].map(a=>a.map(quote).join(';')).join('\r\n');const url=URL.createObjectURL(new Blob([content],{type:'text/csv;charset=utf-8'})),a=document.createElement('a');a.href=url;a.download=filename;document.body.append(a);a.click();a.remove();setTimeout(()=>URL.revokeObjectURL(url),1500);}
function exportBudget(list){const rows=[];for(const p of list)for(const g of p.budget.groups){rows.push([p.name,g.code,g.label,g.presupuesto,g.real,g.presupuesto-g.real,'Subtotal','NO']);for(const c of g.children)rows.push([p.name,c.code,c.label,c.presupuesto,c.real,c.presupuesto-c.real,'Detalle','SÍ']);}csv('presupuesto_vs_real_por_partida.csv',['Proyecto','Código','Partida','Plan USD','Real USD','Diferencia USD','Tipo de fila','Incluir detalle en agregación'],rows);}
function exportCash(list){const periods=filterPeriods(list);let records=[];for(const p of list)for(const g of p.cashflow.groups){const arr=g.children.length?g.children:[g];for(const ch of arr){records.push([p.name,ch.code,ch.label,ch.presupuesto,...periods.map(t=>{let i=p.cashflow.periods.findIndex(x=>(Number.isInteger(p.startYear)&&t.year!=null?(p.startYear+x.yearIndex-1===t.year&&clean(x.month)===clean(t.month)):x.id===t.period));return i<0?0:ch.values[i];})]);}}csv('flujo_caja_detalle_sin_subtotales.csv',['Proyecto','Código','Partida','Ppto OI DOP',...periods.map(t=>t.month+' '+(t.year||'P'+t.period))],records);}
function exportCompare(list){const comp=budgetComparison(list),head=['Código','Partida',...list.flatMap(p=>[p.name+' Plan USD',p.name+' Real USD',p.name+' Diferencia USD'])],rows=[];for(const g of comp.rows){rows.push([g.code,g.label,...list.flatMap(p=>{const v=g.projectGroups.get(p.id);return v?[v.presupuesto,v.real,v.presupuesto-v.real]:['','',''];})]);for(const c of g.children)rows.push([c.code,c.label,...list.flatMap(p=>{const v=c.values.get(p.id);return v?[v.presupuesto,v.real,v.presupuesto-v.real]:['','',''];})]);}rows.push(['','TOTAL GENERAL',...list.flatMap(p=>{const v=comp.totals.get(p.id);return[v.presupuesto,v.real,v.presupuesto-v.real];})]);csv('comparativo_proyectos.csv',head,rows);}
function bindBody(){const list=filtersProjects();$('emptyUpload')?.addEventListener('click',()=>$('fileInput').click());$('enableDemo')?.addEventListener('click',()=>{preview=true;render();});$('demoUpload')?.addEventListener('click',()=>$('fileInput').click());$('dataManage')?.addEventListener('click',()=>openModal());
 document.querySelectorAll('[data-donut]').forEach(b=>b.addEventListener('click',()=>{budgetDonut=b.dataset.donut;render();}));
 document.querySelectorAll('[data-budget-toggle]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.budgetToggle;openBudget.has(v)?openBudget.delete(v):openBudget.add(v);render();}));
 document.querySelectorAll('[data-overview]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.overview;openSummary.has(v)?openSummary.delete(v):openSummary.add(v);render();}));
 document.querySelectorAll('[data-cash]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.cash;openCash.has(v)?openCash.delete(v):openCash.add(v);render();}));
 document.querySelectorAll('[data-compare]').forEach(b=>b.addEventListener('click',()=>{const v=b.dataset.compare;openCompare.has(v)?openCompare.delete(v):openCompare.add(v);render();}));
 document.querySelectorAll('[data-expand]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.expand==='budget')list.forEach(p=>p.budget.groups.forEach(g=>openBudget.add(`${p.id}|${g.code}`)));if(b.dataset.expand==='cash')list.forEach(p=>p.cashflow.groups.forEach(g=>openCash.add(`${p.id}|${g.code}`)));if(b.dataset.expand==='compare')budgetComparison(list).rows.forEach(g=>openCompare.add(g.code));render();}));
 document.querySelectorAll('[data-collapse]').forEach(b=>b.addEventListener('click',()=>{if(b.dataset.collapse==='budget')openBudget.clear();if(b.dataset.collapse==='cash')openCash.clear();if(b.dataset.collapse==='compare')openCompare.clear();render();}));
 $('purchaseFilter')?.addEventListener('change',e=>{purchaseFilter=e.target.value;render();});
 const input=$('searchInput');if(input){input.addEventListener('change',e=>{search=e.target.value;render();});input.addEventListener('keydown',e=>{if(e.key==='Enter'){search=input.value;render();}});}
 $('exportBudget')?.addEventListener('click',()=>exportBudget(list));$('exportCash')?.addEventListener('click',()=>exportCash(list));$('exportCompare')?.addEventListener('click',()=>exportCompare(list));
 $('exportPurchases')?.addEventListener('click',()=>{const rows=list.flatMap(p=>p.purchases.rows.map(r=>({...r,project:p.name}))).filter(r=>purchaseFilter==='__all'||r.estado===purchaseFilter);csv('seguimiento_de_compras.csv',['Proyecto','Partida','Ítem','Orden G','Estado','Proveedor','Monto DOP'],rows.map(r=>[r.project,r.partida,r.item,r.oc,statusText[r.estado],r.proveedor,r.presupuestoDOP]));});
}
function openModal(){renderManager();$('modalBackdrop').hidden=false;}
function closeModal(){$('modalBackdrop').hidden=true;}
function renderManager(){const parent=$('projectManager');if(!saved.length){parent.innerHTML='<div class="no-data">Sin proyectos reales guardados. Carga un Excel para editar sus datos.</div>';return;}parent.innerHTML=saved.map(p=>`<div class="manager-row" data-id="${esc(p.id)}"><div><label>Nombre de iniciativa</label><input class="edit-name" value="${esc(p.name)}" maxlength="120"><small>${esc(p.filename)}</small></div><div><label>Formato</label><select class="edit-format">${['Sirena','Aprezio','Otro','Sin clasificar'].map(v=>`<option ${meta(p).format===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label>Tipo de proyecto</label><select class="edit-type">${['Nueva','Remodelación','Otro','Sin clasificar'].map(v=>`<option ${meta(p).type===v?'selected':''}>${v}</option>`).join('')}</select></div><div><label>Año inicial flujo</label><input type="number" class="edit-year" min="2000" max="2100" placeholder="Sin definir" value="${p.startYear||''}"></div><div class="card-tools"><button class="control-btn save-project">Guardar</button><button class="remove-btn delete-project">Eliminar</button></div></div>`).join('');parent.querySelectorAll('.manager-row').forEach(row=>{row.querySelector('.save-project').addEventListener('click',async()=>{const p=saved.find(x=>x.id===row.dataset.id);const name=row.querySelector('.edit-name').value.trim(),yearStr=row.querySelector('.edit-year').value.trim(),year=yearStr?Number(yearStr):null;if(!name){toast('Escribe un nombre.',true);return;}if(year!==null&&(!Number.isInteger(year)||year<2000||year>2100)){toast('Año no válido.',true);return;}p.name=name;p.format=row.querySelector('.edit-format').value;p.projectType=row.querySelector('.edit-type').value;p.startYear=year;try{await storeProject(p);renderManager();render();toast('Iniciativa actualizada.');}catch(e){toast('Error guardando: '+e.message,true);}});row.querySelector('.delete-project').addEventListener('click',async()=>{const p=saved.find(x=>x.id===row.dataset.id);if(!confirm(`¿Eliminar ${p.name} de este navegador?`))return;try{await dropProject(p.id);saved=saved.filter(x=>x.id!==p.id);if(selected===p.id)selected='__all';renderManager();render();toast('Iniciativa eliminada.');}catch(e){toast('No se pudo eliminar: '+e.message,true);}});});}
async function loadXLSX(){if(window.XLSX)return;await new Promise((yes,no)=>{const s=document.createElement('script');s.src='https://unpkg.com/xlsx@0.18.5/dist/xlsx.full.min.js';s.onload=yes;s.onerror=()=>no(Error('Sin conexión para cargar el lector de Excel.'));document.head.append(s);});}
async function importFiles(files){if(!files.length)return;const button=$('uploadBtn');button.disabled=true;button.textContent='Procesando…';let imported=0;
 for(const f of files){try{if(!/\.xlsx?$/i.test(f.name))throw Error('Admite .xlsx y .xls.');if(f.size>40*1024*1024)throw Error('Límite 40 MB por archivo.');await loadXLSX();const wb=window.XLSX.read(await f.arrayBuffer(),{type:'array',cellDates:true,cellFormula:true});const sheets={};for(const n of wb.SheetNames)sheets[n]=window.XLSX.utils.sheet_to_json(wb.Sheets[n],{header:1,raw:true,defval:null,blankrows:true});const p=parseProject(sheets,f.name);if(!Object.values(p.selected).some(Boolean))throw Error('No se reconoce ninguna de las 3 hojas.');const old=saved.find(x=>x.filename.toLowerCase()===f.name.toLowerCase());if(old&&!confirm(`Ya existe ${old.name}. ¿Actualizar sus datos?`))continue;p.id=old?.id||('ramos_'+(globalThis.crypto?.randomUUID?.()||Date.now()+'_'+imported));p.name=old?.name||p.name;p.format=old?.format||guessFormat(p.name);p.projectType=old?.projectType||guessType(p.name);p.startYear=old?.startYear||null;await storeProject(p);saved=saved.filter(x=>x.id!==p.id);saved.push(p);imported++;}catch(e){console.error(e);toast(`${f.name}: ${e.message}`,true);}}
 button.disabled=false;button.innerHTML='<span>＋</span> Cargar Excel';$('fileInput').value='';saved.sort((a,b)=>a.name.localeCompare(b.name,'es'));if(imported){preview=false;selected='__all';selectedFormat='__all';selectedType='__all';selectedYear='__all';selectedQuarter='__all';render();toast(`${imported} ${imported===1?'iniciativa importada':'iniciativas importadas'} correctamente.`);}else render();}
function attachShell(){document.querySelectorAll('[data-view]').forEach(b=>b.addEventListener('click',()=>{view=b.dataset.view;search='';$('sidebar').classList.remove('open');render();window.scrollTo(0,0);}));
 $('menuBtn').addEventListener('click',()=>$('sidebar').classList.toggle('open'));$('uploadBtn').addEventListener('click',()=>$('fileInput').click());$('fileInput').addEventListener('change',e=>importFiles([...e.target.files]));$('printBtn').addEventListener('click',()=>window.print());$('manageBtn').addEventListener('click',openModal);$('modalClose').addEventListener('click',closeModal);$('modalBackdrop').addEventListener('click',e=>{if(e.target.id==='modalBackdrop')closeModal();});document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});
 $('projectSelect').addEventListener('change',e=>{selected=e.target.value;render();});$('formatSelect').addEventListener('change',e=>{selectedFormat=e.target.value;render();});$('typeSelect').addEventListener('change',e=>{selectedType=e.target.value;render();});$('yearSelect').addEventListener('change',e=>{selectedYear=e.target.value;render();});$('quarterSelect').addEventListener('change',e=>{selectedQuarter=e.target.value;render();});}
async function init(){attachShell();try{saved=await allProjects();saved.sort((a,b)=>a.name.localeCompare(b.name,'es'));if(saved.length)preview=false;}catch(e){storageOk=false;toast('El navegador no permite guardar datos localmente: '+e.message,true);}render();}
init();
